### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by PabloAlice** [windingtree/wt-ui-react#12]
**Is your feature request related to a problem? Please describe.**
We need a Footer component to use it across all our apps

**Describe the solution you'd like**
Create a Footer component

**Additional context**
![image](https://user-images.githubusercontent.com/11988423/47160162-ba40cf80-d2c5-11e8-8155-ba59eb450dd7.png)

**Comment by MatiasOS** [comment]
I have noticed that sometimes the list changes. 
There is an extra column `developers`, that it have a dynamic link to current github repo.  
The best is to have all the content inside and enable (or disable) on demand.

The API will look similar to: 
`<Footer source='wt-react-ui' solutions developers lif comunity />`

**Comment by menschikov** [comment]
I think proposed approach with dynamic content should work! The footer for website should be always the same but it can be simpler for our apps, even with own column headers, e.g. booking app footer can have absolutely new (own) columns in footer
