### ISSUE TITLE
Card

### ISSUE THREAD

**Issue by PabloAlice** [windingtree/wt-ui-react#13]
**Is your feature request related to a problem? Please describe.**
We need a Card component to use across our apps

**Describe the solution you'd like**
build a Card component keeping an eye on how we use it on windingTree homepage and wt-explorer

**Additional context**
![image](https://user-images.githubusercontent.com/11988423/47185649-699c9700-d304-11e8-9fe8-b09bb49146ea.png)

**Comment by beogip** [comment]
sure
