### ISSUE TITLE
Update deploy keys in Travis

### ISSUE THREAD

**Issue by menschikov** [windingtree/wt-ui-react#92]
Current deploy tokens are generated by Mati and after he was excluded from npm organisation Travis can't deploy the package to npm anymore. We need to update npm tokes as long as other tokes generated by Mati
![image](https://user-images.githubusercontent.com/4557491/54133564-1f918a80-4438-11e9-9162-8d620c118ad8.png)

**Comment by JirkaChadima** [comment]
Reconfigured on Travis. The package should be properly published on every new tag
